apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-app
  #namespace: simple-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-go-app
  template:
    metadata:
      labels:
        app: simple-go-app
    spec:
      containers:
      - name: simple-go-app
        image: gcr.io/cluster-01-290863/test/testimage:signed
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-app
  #namespace: simple-go-app
spec:
  selector:
    app: simple-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
